spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:forum
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  h2:
    console:
      enabled: true

#spring:
#  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/forumAlura?createDatabaseIfNotExist=true
#    username: root
#    password: root
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
  flyway.locations.filesystem: db/migration

